apiVersion: v1
kind: Service
metadata:
  name: testsvc
  labels:
    feladat.banzaicloud.io/ingress: secure
  annotations:
    domain: ug0jcqu276koi.spotguidetest.beta.banzaicloud.io
    email: janos.sarusikis@gmail.com 
spec:
  selector:
    app: MyApp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376