apiVersion: v1
kind: Service
metadata:
  name: testsvc
  labels:
    feladat.banzaicloud.io/ingress: secure
  annotations:
    domain: example.com
    email: janos.sarusikis@gmail.com 
spec:
  selector:
    app: MyApp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376