# permissions for end users to view customingressmanagers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: customingressmanager-viewer-role
rules:
- apiGroups:
  - webapp.feladat.banzaicloud.io
  resources:
  - customingressmanagers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - webapp.feladat.banzaicloud.io
  resources:
  - customingressmanagers/status
  verbs:
  - get
